name: This is a pipeline
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: This is a print 
        run: |
          echo "welcome to pipeline world234"
          echo "this is no 1 yaari"
         
      - name: install cowsay  
        run:  sudo apt-get install cowsay -y

      - name: ASCII Program 
        run:  cowsay -f dragon "this is a dragon" >> dragon.txt

      - name: read file
        run: cat dragon.txt