name: This is a pipeline
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: This is a print 
        run: echo "welcome to pipeline world"

      - name: This is a list of files
        run: ls
